name: Test of proof_of_travel_controller
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python 3.7.11
        uses: actions/setup-python@v4
        with:
            python-version: '3.7.11'
      - run: docker run mysql
      - name: Install requirements
        run: pip install -r install/reqs.txt
      - name: Install data of database
        run: sh ./install/db-init-and-populate.sh
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest app/test/test_proof_of_controller.py
