name: Test of proof_of_travel_controller
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.7.11","3.10"]
    env:
      DB_USER: root
      DB_PASSWORD: root
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
            python-version: ${{matrix.python-version}}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install requirements
        run: pip install -r install/reqs.txt
      - name: Install the database
        run: |
         sudo /etc/init.d/mysql start
         mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '';"
         echo "Création base de données + utilisateurs"
         sudo mysql -e "CREATE DATABASE yackunivdb;"
         sudo mysql -e "CREATE USER 'admin_yackuniv'@'localhost' IDENTIFIED BY 'YackUnivDbPass';FLUSH PRIVILEGES;"
         sudo mysql -e "GRANT ALL PRIVILEGES ON yackunivdb.* TO 'admin_yackuniv'@'localhost';FLUSH PRIVILEGES;"

         echo "Initialisation de la base de données"

         
         export FLASK_APP=app/yacka.py
         export FLASK_ENV=local
         flask db init
         flask db migrate
         flask db upgrade

         echo "Population de la base"
         mysql -u admin_yackuniv -p'YackUnivDbPass' -D yackunivdb < install/yackunivdbdump.sql
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest app/test/test_proof_of_travel_controller.py
